name: Pull Request Created Workflow

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Ajoutez ici les étapes de votre workflow, par exemple :
      - name: Run linting
        run: |
          # Commandes pour effectuer le linting du code
